/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestSupabaseRouteImport } from './routes/test-supabase'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppTenantsRouteImport } from './routes/app.tenants'
import { Route as AppSupportRouteImport } from './routes/app.support'
import { Route as AppSubscriptionsRouteImport } from './routes/app.subscriptions'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppServiceRequestsRouteImport } from './routes/app.service-requests'
import { Route as AppPropertiesRouteImport } from './routes/app.properties'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppLeasesRouteImport } from './routes/app.leases'
import { Route as AppInvoicesRouteImport } from './routes/app.invoices'
import { Route as AppEstimatesRouteImport } from './routes/app.estimates'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppContractorsRouteImport } from './routes/app.contractors'
import { Route as AppAuditLogsRouteImport } from './routes/app.audit-logs'
import { Route as AppAppointmentsRouteImport } from './routes/app.appointments'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppPropertiesIdRouteImport } from './routes/app.properties.$id'

const TestSupabaseRoute = TestSupabaseRouteImport.update({
  id: '/test-supabase',
  path: '/test-supabase',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTenantsRoute = AppTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionsRoute = AppSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppServiceRequestsRoute = AppServiceRequestsRouteImport.update({
  id: '/service-requests',
  path: '/service-requests',
  getParentRoute: () => AppRoute,
} as any)
const AppPropertiesRoute = AppPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppLeasesRoute = AppLeasesRouteImport.update({
  id: '/leases',
  path: '/leases',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppEstimatesRoute = AppEstimatesRouteImport.update({
  id: '/estimates',
  path: '/estimates',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContractorsRoute = AppContractorsRouteImport.update({
  id: '/contractors',
  path: '/contractors',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditLogsRoute = AppAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsRoute = AppAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppPropertiesIdRoute = AppPropertiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPropertiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/test-supabase': typeof TestSupabaseRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/audit-logs': typeof AppAuditLogsRoute
  '/app/contractors': typeof AppContractorsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/estimates': typeof AppEstimatesRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/leases': typeof AppLeasesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/properties': typeof AppPropertiesRouteWithChildren
  '/app/service-requests': typeof AppServiceRequestsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/subscriptions': typeof AppSubscriptionsRoute
  '/app/support': typeof AppSupportRoute
  '/app/tenants': typeof AppTenantsRoute
  '/app/users': typeof AppUsersRoute
  '/app/properties/$id': typeof AppPropertiesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/test-supabase': typeof TestSupabaseRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/audit-logs': typeof AppAuditLogsRoute
  '/app/contractors': typeof AppContractorsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/estimates': typeof AppEstimatesRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/leases': typeof AppLeasesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/properties': typeof AppPropertiesRouteWithChildren
  '/app/service-requests': typeof AppServiceRequestsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/subscriptions': typeof AppSubscriptionsRoute
  '/app/support': typeof AppSupportRoute
  '/app/tenants': typeof AppTenantsRoute
  '/app/users': typeof AppUsersRoute
  '/app/properties/$id': typeof AppPropertiesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/test-supabase': typeof TestSupabaseRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/audit-logs': typeof AppAuditLogsRoute
  '/app/contractors': typeof AppContractorsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/estimates': typeof AppEstimatesRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/leases': typeof AppLeasesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/properties': typeof AppPropertiesRouteWithChildren
  '/app/service-requests': typeof AppServiceRequestsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/subscriptions': typeof AppSubscriptionsRoute
  '/app/support': typeof AppSupportRoute
  '/app/tenants': typeof AppTenantsRoute
  '/app/users': typeof AppUsersRoute
  '/app/properties/$id': typeof AppPropertiesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/test-supabase'
    | '/app/analytics'
    | '/app/appointments'
    | '/app/audit-logs'
    | '/app/contractors'
    | '/app/dashboard'
    | '/app/estimates'
    | '/app/invoices'
    | '/app/leases'
    | '/app/notifications'
    | '/app/properties'
    | '/app/service-requests'
    | '/app/settings'
    | '/app/subscriptions'
    | '/app/support'
    | '/app/tenants'
    | '/app/users'
    | '/app/properties/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/test-supabase'
    | '/app/analytics'
    | '/app/appointments'
    | '/app/audit-logs'
    | '/app/contractors'
    | '/app/dashboard'
    | '/app/estimates'
    | '/app/invoices'
    | '/app/leases'
    | '/app/notifications'
    | '/app/properties'
    | '/app/service-requests'
    | '/app/settings'
    | '/app/subscriptions'
    | '/app/support'
    | '/app/tenants'
    | '/app/users'
    | '/app/properties/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/test-supabase'
    | '/app/analytics'
    | '/app/appointments'
    | '/app/audit-logs'
    | '/app/contractors'
    | '/app/dashboard'
    | '/app/estimates'
    | '/app/invoices'
    | '/app/leases'
    | '/app/notifications'
    | '/app/properties'
    | '/app/service-requests'
    | '/app/settings'
    | '/app/subscriptions'
    | '/app/support'
    | '/app/tenants'
    | '/app/users'
    | '/app/properties/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TestSupabaseRoute: typeof TestSupabaseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-supabase': {
      id: '/test-supabase'
      path: '/test-supabase'
      fullPath: '/test-supabase'
      preLoaderRoute: typeof TestSupabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tenants': {
      id: '/app/tenants'
      path: '/tenants'
      fullPath: '/app/tenants'
      preLoaderRoute: typeof AppTenantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/support': {
      id: '/app/support'
      path: '/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/subscriptions': {
      id: '/app/subscriptions'
      path: '/subscriptions'
      fullPath: '/app/subscriptions'
      preLoaderRoute: typeof AppSubscriptionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/service-requests': {
      id: '/app/service-requests'
      path: '/service-requests'
      fullPath: '/app/service-requests'
      preLoaderRoute: typeof AppServiceRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/properties': {
      id: '/app/properties'
      path: '/properties'
      fullPath: '/app/properties'
      preLoaderRoute: typeof AppPropertiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leases': {
      id: '/app/leases'
      path: '/leases'
      fullPath: '/app/leases'
      preLoaderRoute: typeof AppLeasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invoices': {
      id: '/app/invoices'
      path: '/invoices'
      fullPath: '/app/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estimates': {
      id: '/app/estimates'
      path: '/estimates'
      fullPath: '/app/estimates'
      preLoaderRoute: typeof AppEstimatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contractors': {
      id: '/app/contractors'
      path: '/contractors'
      fullPath: '/app/contractors'
      preLoaderRoute: typeof AppContractorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit-logs': {
      id: '/app/audit-logs'
      path: '/audit-logs'
      fullPath: '/app/audit-logs'
      preLoaderRoute: typeof AppAuditLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/appointments': {
      id: '/app/appointments'
      path: '/appointments'
      fullPath: '/app/appointments'
      preLoaderRoute: typeof AppAppointmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/properties/$id': {
      id: '/app/properties/$id'
      path: '/$id'
      fullPath: '/app/properties/$id'
      preLoaderRoute: typeof AppPropertiesIdRouteImport
      parentRoute: typeof AppPropertiesRoute
    }
  }
}

interface AppPropertiesRouteChildren {
  AppPropertiesIdRoute: typeof AppPropertiesIdRoute
}

const AppPropertiesRouteChildren: AppPropertiesRouteChildren = {
  AppPropertiesIdRoute: AppPropertiesIdRoute,
}

const AppPropertiesRouteWithChildren = AppPropertiesRoute._addFileChildren(
  AppPropertiesRouteChildren,
)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAppointmentsRoute: typeof AppAppointmentsRoute
  AppAuditLogsRoute: typeof AppAuditLogsRoute
  AppContractorsRoute: typeof AppContractorsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEstimatesRoute: typeof AppEstimatesRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppLeasesRoute: typeof AppLeasesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPropertiesRoute: typeof AppPropertiesRouteWithChildren
  AppServiceRequestsRoute: typeof AppServiceRequestsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSubscriptionsRoute: typeof AppSubscriptionsRoute
  AppSupportRoute: typeof AppSupportRoute
  AppTenantsRoute: typeof AppTenantsRoute
  AppUsersRoute: typeof AppUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAppointmentsRoute: AppAppointmentsRoute,
  AppAuditLogsRoute: AppAuditLogsRoute,
  AppContractorsRoute: AppContractorsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEstimatesRoute: AppEstimatesRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppLeasesRoute: AppLeasesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPropertiesRoute: AppPropertiesRouteWithChildren,
  AppServiceRequestsRoute: AppServiceRequestsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSubscriptionsRoute: AppSubscriptionsRoute,
  AppSupportRoute: AppSupportRoute,
  AppTenantsRoute: AppTenantsRoute,
  AppUsersRoute: AppUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TestSupabaseRoute: TestSupabaseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
